# Generated by Django 4.2.4 on 2023-10-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=30, unique=True, verbose_name='Номер телефона'),
        ),
    ]
