# Generated by Django 4.2.4 on 2023-08-31 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
