# Generated by Django 4.2.4 on 2023-09-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_weight_alter_product_filters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Weight'),
        ),
    ]
