# Generated by Django 4.2.4 on 2023-09-05 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_size_alter_product_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_product_card_text', models.CharField(max_length=10)),
                ('linked_product_card_text', models.CharField(max_length=10)),
                ('linked_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_product', to='shop.product', verbose_name='Linked product')),
                ('main_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='linked_product', to='shop.product', verbose_name='Main product')),
            ],
            options={
                'verbose_name': 'Link Product',
                'verbose_name_plural': 'Link Products',
            },
        ),
    ]
