# Generated by Django 4.2.4 on 2023-09-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_productlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='preview_image',
            field=models.BooleanField(default=False),
        ),
    ]
