# Generated by Django 4.2.4 on 2023-09-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_productimage_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buy_together',
            field=models.ManyToManyField(blank=True, to='shop.product', verbose_name='Buy Together'),
        ),
    ]
