# Generated by Django 4.2.4 on 2023-09-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_buy_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ingredient')),
                ('name', models.CharField(max_length=32, verbose_name='Назва')),
                ('name_en', models.CharField(max_length=32, null=True, verbose_name='Назва')),
                ('name_ua', models.CharField(max_length=32, null=True, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
            },
        ),
    ]
