# Generated by Django 4.2.4 on 2023-09-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_productingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='shop.productingredient', verbose_name='Ingredients'),
        ),
    ]
