# Generated by Django 4.2.4 on 2023-09-16 20:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_additionalinfo_product_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalinfo',
            name='text_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Основной Текст'),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='text_ua',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Основной Текст'),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='title_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='title_ua',
            field=models.CharField(max_length=30, null=True, verbose_name='Title'),
        ),
    ]
