# Generated by Django 4.2.4 on 2023-09-16 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_additionalinfo_text_en_additionalinfo_text_ua_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalinfo',
            options={'verbose_name': 'Additional Info', 'verbose_name_plural': 'Additional Infos'},
        ),
    ]
