# Generated by Django 4.2.4 on 2023-09-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_additionalinfo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('g', 'grams'), ('ml', 'milliliters')], default='g', max_length=10, verbose_name='Unit'),
        ),
    ]
